---
# tasks file for base_install
#
- name: Install base packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: latest
    update_cache: yes

- name: Install extended base packages
  community.general.pacman:
    name: "{{ extended_base_packages }}"
    state: latest
    update_cache: yes
