---
# tasks file for yay
#TODO make it possible to fetch a specific version of yay
#TODO split building and installing of the package into two tasks to make it more clear, when sudo privileges are required

- name: "Determine if yay is already installed (check for /usr/bin/yay)"
  stat:
    path: /usr/bin/yay
  register: yay_present

- name: "Fetch package yay from AUR"
  local_action:
    module: ansible.builtin.git
    repo: https://aur.archlinux.org/yay.git
    clone: yes
    dest: /tmp/yay
      #version: "{{ yay_version }}" #FIXME
  when: not yay_present.stat.exists

#TODO it could be, that become: true is required
- name: "Install yay via makepkg -si"
  local_action:
    module: ansible.builtin.command makepkg -i --noconfirm
    args:
      chdir: /tmp/yay
  when: not yay_present.stat.exists
