---
# tasks file for yay

#TODO move this also into the user role!
- name: "Create user for installing AUR packages"
  ansible.builtin.user:
    name: "{{ aur_user_name }}"
    state: present
    system: yes

- name: "Allow user {{ aur_user_name }} passwordless access to pacman"
  lineinfile:
    group: root
    owner: root
    mode: 0644
    path: "/etc/sudoers.d/{{ aur_user_name }}"
    create: yes
    state: present
    line: "{{ aur_user_name }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    validate: "/usr/sbin/visudo -cf %s"

- name: "Determin if yay is already installed (check for /usr/bin/yay)"
  stat:
    path: /usr/bin/yay
  register: yay_present

- name: "Fetch package yay from AUR"
  become: true
  become_user: "{{ aur_user_name }}"
  ansible.builtin.git:
    clone: yes
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
      #version: "{{ yay_version }}" #FIXME
  when: not yay_present.stat.exists

- name: "Install yay via makepkg -si"
  become: true
  become_user: "{{ aur_user_name }}"
  ansible.builtin.shell: |
    cd /tmp/yay/
    makepkg -si --noconfirm
  when: not yay_present.stat.exists
