---
#basic setup on new machines
- name: Setup new system
  hosts: target
  connection: local

  vars_prompt:
    - name: username
      prompt: "Provide the username"
      private: true

    - name: groupname
      prompt: "Provide the groupname"
      private: true

    - name: password
      prompt: "Provide the password for the user"
      encrypt: sha512_crypt
      confirm: true
      salt_size: 7
      unsafe: yes
      private: true

  roles:
    - name: "Install base packages"
      role: base_install
      become: true
      tags:
        - base
        - initial

    - name: "Setup user {{ username }}"
      role: user
      become: true
      vars:
        user:
          name: "{{ username }}"
          group: "{{ groupname }}"
          additional_groups: []
          password: "{{ password }}"
          systemuser: false
      tags:
        - base
        - initial
        - create_user

    - name: "Install desktop environment & xmonad"
      role: xmonad
      become: true
      tags:
        - base
        - initial
        - gnome
        - xmonad

    - name: "Install yay"
      role: yay
      become: true
      vars:
        aur_user_name: "aur_user"
      tags:
        - yay
        - base
        - initial

  tasks:
    - name: "Install pacman tools"
      become: true
      community.general.pacman:
        name: "{{ pacman_tools }}"
        state: latest
        update_cache: yes
      tags:
        - base
        - initial

    - name: "Install development packages"
      become: true
      community.general.pacman:
        name: "{{ development_packages_pacman }}"
        state: latest
        update_cache: yes
      tags:
        - tools

    - name: "Install packages from AUR"
      yay:
        name: "{{ aur_tools }}"
        state: latest
      tags:
        - test
    - name: "Create folder /home/{{ username }}/backgrounds/"
      ansible.builtin.file:
        path: "/home/{{ username }}/backgrounds"
        state: directory
        mode: '0755'
      register: background_directory
      become: false
      tags:
        - desktop

    - name: "Download backgrounds"
      ansible.builtin.get_url:
        url: "{{ dropbox_background_folder_url }}"
        dest: "/home/{{ username }}/Downloads/backgrounds.zip"
      become: false
      tags:
        - desktop

    - name: "Unzip backgrounds.zip to /home/{{ user.name }}/backgrounds/"
      ansible.builtin.unarchive:
        src: "/home/{{ user.name }}/Downloads/backgrounds.zip"
        remote_src: yes
        dest: "/home/{{ username }}/backgrounds/"
        group: groupname
        owner: username
      become: false
      register: unzip_result
      failed_when:
        - '"extracting" not in unzip_result.extract_results.out'
      tags:
        - desktop



#TODO
# install pre-X minimal setup
# install gnome + xmonad + picom + xmobar
# [x] install and configure yay
# install aur packages via yay
# setup gdm config
# setup dotfiles
